// src/cards.js
// Card and benefit data — shared by card finder (main.js) and tracker (tracker.js).
// cadence values: 'monthly' | 'semi-annual' | 'annual' | 'excluded'

export const CARDS = [
  {
    id: 'csp',
    name: 'Chase Sapphire Preferred®',
    issuer: 'Chase',
    annualFee: 95,
    annualFeeDisplay: '$95/yr',
    signupBonus: '75,000 pts (~$938)',
    applyUrl: 'https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred',
    officialUrl: 'https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred',
    why: 'The gold standard starter travel card. Dining, grocery, and streaming all earn 3x transferable Chase points worth up to 2¢ each via airline partners. The $50 hotel credit and DashPass value quietly bring the real cost well below $95. The 10% anniversary points bonus is an underrated perk.',
    perks: ['5x on Chase Travel','3x Dining worldwide','3x Online grocery','3x Select streaming','2x Other travel','1x Everything else','10% anniversary points bonus','Trip cancellation up to $10k/traveler','Primary auto rental coverage','No foreign transaction fees'],
    credits: [
      { name: '$50 Annual Hotel Credit', desc: 'Statement credit on hotel stays booked via Chase Travel each account anniversary year', value: 50, cadence: 'annual' },
      { name: 'DashPass + DoorDash Promos', desc: '12 months free DashPass ($120 value) + $10/mo DoorDash non-restaurant promo through Dec 31, 2027 ($120 value)', value: 240, cadence: 'monthly' },
    ],
    totalCreditValue: 290,
    earn: { groceries:3, dining:3, flights:5, hotels:2, gas:1, streaming:3, shopping:1, everything:1 },
    pointValue: 0.0125,
    creditReq: ['good','excellent'],
    tags: { goal:['travel','both'], spend:['dining','groceries','travel','everything'], fee:['low','high'], travel:['sometimes','often'] }
  },
  {
    id: 'csr',
    name: 'Chase Sapphire Reserve®',
    issuer: 'Chase',
    annualFee: 795,
    annualFeeDisplay: '$795/yr',
    signupBonus: '125,000 pts (~$1,250)',
    applyUrl: 'https://account.chase.com/sapphire/reserve/benefits',
    officialUrl: 'https://account.chase.com/sapphire/reserve/benefits',
    why: 'The $795 fee is real — but so are the credits. The $300 travel credit drops your effective cost to $495 immediately. Stack the $500 Edit hotel credit, $300 dining, $300 StubHub, and $420 DoorDash value and frequent travelers can extract well over $2,700 annually. The new 8x on Chase Travel and 4x booking direct are the best earn rates on the market. Best for people who travel often AND dine out regularly.',
    perks: ['8x on Chase Travel (flights, hotels, rental cars)','4x booking directly with airlines or hotels','3x on dining worldwide','Chase Sapphire Lounge + Priority Pass (1,300+ lounges)','$500 The Edit hotel credit (split semi-annually)','IHG Platinum Elite status through Dec 2027','Apple TV+ & Apple Music complimentary','No foreign transaction fees'],
    credits: [
      { name: '$300 Annual Travel Credit', desc: 'Auto-applied to any travel purchase — flights, hotels, Uber, parking, tolls', value: 300, cadence: 'annual' },
      { name: '$500 The Edit Hotel Credit', desc: '$250 semi-annually on 2+ night prepaid stays at The Edit collection via Chase Travel (includes breakfast, $100 property credit, room upgrade)', value: 500, cadence: 'semi-annual' },
      { name: '$300 Annual Dining Credit', desc: '$150 semi-annually at Sapphire Reserve Exclusive Tables restaurants via OpenTable (enrollment required)', value: 300, cadence: 'semi-annual' },
      { name: '$300 Annual StubHub Credit', desc: '$150 semi-annually on concert and event tickets at StubHub and viagogo (activation required)', value: 300, cadence: 'semi-annual' },
      { name: '$420 DoorDash Value', desc: 'Up to $25/mo in DoorDash promos ($300/yr) + complimentary DashPass membership ($120 value) through Dec 31, 2027', value: 420, cadence: 'monthly' },
      { name: '$250 Apple TV+ & Apple Music', desc: 'Complimentary subscriptions to both services through June 22, 2027', value: 250, cadence: 'excluded' },
      { name: '$120 Lyft Credit', desc: '$10/mo in Lyft in-app credits through September 30, 2027', value: 120, cadence: 'monthly' },
      { name: '$120 Peloton Membership Credit', desc: '$10/mo toward Peloton All-Access, App One, App+, or other memberships through Dec 31, 2027', value: 120, cadence: 'monthly' },
      { name: 'Global Entry, TSA PreCheck or NEXUS', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
      { name: 'Chase Sapphire Lounge + Priority Pass', desc: 'Unlimited access to Chase Sapphire Lounges + 1,300+ Priority Pass lounges. Includes 2 free guests per visit.', value: 429, cadence: 'excluded' },
      { name: 'IHG Platinum Elite Status', desc: 'Complimentary through December 31, 2027 — room upgrades and late checkout', value: 0, cadence: 'excluded' },
    ],
    totalCreditValue: 2769,
    earn: { groceries:1, dining:3, flights:4, hotels:4, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.015,
    creditReq: ['excellent'],
    tags: { goal:['travel','both'], spend:['dining','travel'], fee:['high'], travel:['often'] }
  },
  {
    id: 'amex-plat',
    name: 'The Platinum Card®',
    issuer: 'American Express',
    annualFee: 895,
    annualFeeDisplay: '$895/yr',
    signupBonus: '80,000 pts (~$800)',
    applyUrl: '#',
    officialUrl: 'https://www.americanexpress.com/us/credit-cards/card/platinum/',
    why: 'On paper, $895 is steep. In practice, the credits stack fast — $600 in hotel credits, $400 Resy dining, $300 digital entertainment, $200 airline fees, $200 Uber Cash, $120 Uber One, $300 Equinox, $155 Walmart+. Road warriors who use most of them can extract well over $2,000 in annual value. The 5x on flights is unmatched — but note it only applies to flights booked directly with airlines or via Amex Travel, not hotels booked outside Amex.',
    perks: ['5x on flights booked directly with airlines or via Amex Travel','5x on prepaid hotels booked via Amex Travel','1x on everything else','Centurion Lounge + Priority Pass (1,550+ lounges)','10 Delta SkyClub visits/yr (eligible Delta flights)','Fine Hotels + Resorts benefits','Hilton & Marriott Gold status'],
    credits: [
      { name: '$600 Annual Hotel Credit', desc: '$300 semi-annually on prepaid Fine Hotels + Resorts or The Hotel Collection bookings via Amex Travel (2-night minimum for Hotel Collection)', value: 600, cadence: 'semi-annual' },
      { name: '$400 Resy Dining Credit', desc: '$100/quarter at U.S. Resy-affiliated restaurants (enrollment required)', value: 400, cadence: 'quarterly' },
      { name: '$300 Digital Entertainment Credit', desc: '$25/mo toward Disney+, Hulu, ESPN+, Peacock, NYT, WSJ, Paramount+, YouTube Premium, or YouTube TV (enrollment required)', value: 300, cadence: 'monthly' },
      { name: '$200 Airline Fee Credit', desc: 'Incidental fees (checked bags, seat upgrades, lounge day passes) on one selected airline per year', value: 200, cadence: 'annual' },
      { name: '$200 Uber Cash', desc: '$15/mo + $20 bonus in December for U.S. Uber rides or Uber Eats', value: 200, cadence: 'monthly' },
      { name: '$155 Walmart+ Credit', desc: '$12.95/mo Walmart+ membership covered (includes free delivery + Paramount+ Essential)', value: 155, cadence: 'monthly' },
      { name: '$120 Uber One Credit', desc: 'Covers the full cost of an Uber One membership ($9.99/mo or $96/yr)', value: 120, cadence: 'monthly' },
      { name: '$100 Saks Fifth Avenue Credit', desc: '$50 bi-annually (Jan–Jun and Jul–Dec) at Saks Fifth Avenue in-store or online', value: 100, cadence: 'semi-annual' },
      { name: '$300 Equinox Credit', desc: '$25/mo toward Equinox gym membership or Equinox+ app (enrollment required)', value: 300, cadence: 'monthly' },
      { name: '$209 CLEAR+ Credit', desc: 'Annual CLEAR+ membership for expedited airport security (subject to auto-renewal)', value: 209, cadence: 'annual' },
      { name: 'Global Entry or TSA PreCheck', desc: '$120 credit for Global Entry every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
      { name: 'Global Lounge Collection', desc: 'Centurion Lounges, Priority Pass, 10 Delta SkyClub visits — estimated $850+ annual value', value: 850, cadence: 'excluded' },
    ],
    totalCreditValue: 3769,
    earn: { groceries:1, dining:1, flights:5, hotels:5, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.01,
    creditReq: ['excellent'],
    tags: { goal:['travel'], spend:['travel'], fee:['high'], travel:['often'] }
  },
  {
    id: 'amex-gold',
    name: 'American Express® Gold Card',
    issuer: 'American Express',
    annualFee: 325,
    annualFeeDisplay: '$325/yr',
    signupBonus: '60,000 pts (~$600)',
    applyUrl: '#',
    officialUrl: 'https://www.americanexpress.com/us/credit-cards/card/gold-card/',
    why: 'If your biggest monthly expenses are groceries and restaurants, no card touches this one. Four points per dollar in both categories is the highest earn rate you\'ll find. The $120 dining credit, $120 Uber Cash, $84 Dunkin\', and $100 Resy credit together total $424 — which more than covers the $325 annual fee for people who actually use them.',
    perks: ['4x at restaurants worldwide (up to $50k/yr)','4x at US supermarkets (up to $25k/yr)','3x on flights booked directly with airlines or AmexTravel.com','2x on prepaid hotels booked via AmexTravel.com','1x on everything else','No foreign transaction fees','Baggage insurance'],
    credits: [
      { name: '$120 Dining Credit', desc: '$10/mo at Grubhub, The Cheesecake Factory, Goldbelly, Wine.com, or Five Guys (enrollment required)', value: 120, cadence: 'monthly' },
      { name: '$120 Uber Cash', desc: '$10/mo in Uber Cash for U.S. Uber Eats or Uber rides (must add card to Uber app)', value: 120, cadence: 'monthly' },
      { name: '$100 Resy Credit', desc: '$50 semi-annually for in-person dining at U.S. Resy-affiliated restaurants (enrollment required)', value: 100, cadence: 'semi-annual' },
      { name: '$84 Dunkin\' Credit', desc: '$7/mo at U.S. Dunkin\' locations (enrollment required)', value: 84, cadence: 'monthly' },
    ],
    totalCreditValue: 424,
    earn: { groceries:4, dining:4, flights:3, hotels:2, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.01,
    creditReq: ['good','excellent'],
    tags: { goal:['travel','both','cashback'], spend:['groceries','dining'], fee:['low','high'], travel:['never','sometimes','often'] }
  },
  {
    id: 'venture-x',
    name: 'Capital One Venture X',
    issuer: 'Capital One',
    annualFee: 395,
    annualFeeDisplay: '$395/yr',
    signupBonus: '75,000 miles (~$750)',
    applyUrl: '#',
    officialUrl: 'https://www.capitalone.com/credit-cards/venture-x/',
    why: 'The $300 travel credit and 10,000 anniversary miles together more than offset the $395 fee for most travelers. Important 2026 update: free guest lounge access was removed as of February 2026 — guests now cost $35-45/visit unless you spend $75k/yr on the card. Still excellent for solo travelers or couples who each hold their own card. The flat 2x on everything and 15+ transfer partners make it the simplest premium card on the market.',
    perks: ['10x Hotels & rental cars via C1 Travel','5x Flights via C1 Travel','2x on everything else','Capital One Lounges + Priority Pass (primary cardholder only)','Cell phone protection','No foreign transaction fees','Hertz President\'s Circle status'],
    credits: [
      { name: '$300 Annual Travel Credit', desc: 'Statement credit for bookings through Capital One Travel (flights, hotels, rental cars). Resets on card anniversary, not calendar year.', value: 300, cadence: 'annual' },
      { name: '10,000 Anniversary Miles', desc: 'Deposited every account anniversary (~$100 in travel value at 1¢/mile, or up to $185 via transfer partners)', value: 100, cadence: 'annual' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4-5 years (~$25/yr value)', value: 25, cadence: 'excluded' },
      { name: 'Priority Pass + Capital One Lounges', desc: 'Unlimited access for primary cardholder only. Note: as of Feb 2026, guests cost $35/visit at Priority Pass and $45/visit at Capital One Lounges (free only at $75k annual spend)', value: 300, cadence: 'excluded' },
    ],
    totalCreditValue: 725,
    earn: { groceries:2, dining:2, flights:5, hotels:10, gas:2, streaming:2, shopping:2, everything:2 },
    pointValue: 0.01,
    creditReq: ['excellent'],
    tags: { goal:['travel','both'], spend:['travel','everything'], fee:['high'], travel:['often','sometimes'] }
  },
  {
    id: 'double-cash',
    name: 'Citi Double Cash®',
    issuer: 'Citi',
    annualFee: 0,
    annualFeeDisplay: 'No annual fee',
    signupBonus: '$200 cash back',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-double-cash-credit-card',
    why: 'The best no-fee cash back card, no debate. Two percent on everything, every time — 1% when you buy, 1% when you pay. No categories to remember, no caps, no fee. Bonus: earns 5% total on hotels, car rentals, and attractions booked through Citi Travel. Perfect as your main card or the catch-all you use when nothing else earns better.',
    perks: ['2% on all purchases (1% on buy + 1% on pay)','5% total on Citi Travel hotels & car rentals','No annual fee','No category limits or caps','Convert to Citi ThankYou Points','No minimum to redeem'],
    credits: [],
    totalCreditValue: 0,
    earn: { groceries:2, dining:2, flights:2, hotels:5, gas:2, streaming:2, shopping:2, everything:2 },
    pointValue: 0.01,
    creditReq: ['fair','good','excellent'],
    tags: { goal:['cashback','both'], spend:['everything','groceries','dining','gas'], fee:['none'], travel:['never','sometimes'] }
  },
  {
    id: 'cfu',
    name: 'Chase Freedom Unlimited®',
    issuer: 'Chase',
    annualFee: 0,
    annualFeeDisplay: 'No annual fee',
    signupBonus: '$250 cash back',
    applyUrl: '#',
    officialUrl: 'https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited',
    why: 'An underrated no-fee card — especially if you\'re pairing it with a Sapphire. Your Freedom Unlimited earnings convert to Chase Ultimate Rewards points alongside a Sapphire, which can be worth up to 2¢ each via airline transfers. As a standalone card, the 3% on dining is genuinely great. The 6-month DashPass trial is a nice bonus.',
    perks: ['5% on travel via Chase','3% dining & drugstores','1.5% on everything else','No annual fee','Pairs with Sapphire for point transfers','6 months free DashPass','Cell phone protection'],
    credits: [
      { name: '6 Months Free DashPass', desc: 'Auto-enrolls at monthly rate after 6 months. Plus $10/quarter off non-restaurant DoorDash orders through Dec 31, 2027', value: 60, cadence: 'excluded' },
    ],
    totalCreditValue: 60,
    earn: { groceries:1.5, dining:3, flights:5, hotels:1.5, gas:1.5, streaming:1.5, shopping:1.5, everything:1.5 },
    pointValue: 0.01,
    creditReq: ['fair','good','excellent'],
    tags: { goal:['cashback','both'], spend:['dining','everything','groceries'], fee:['none'], travel:['never','sometimes'] }
  },
  {
    id: 'delta-blue',
    name: 'Delta SkyMiles® Blue American Express Card',
    issuer: 'American Express',
    annualFee: 0,
    annualFeeDisplay: 'No annual fee',
    signupBonus: '10,000 miles (~$120)',
    applyUrl: '#',
    officialUrl: 'https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-blue-american-express-card/',
    why: 'The only Delta card with no annual fee. Simple 2x on Delta purchases and dining — nothing fancy, but it costs nothing to hold and keeps your SkyMiles account active. Best for occasional Delta flyers who want to earn miles without committing to an annual fee. If you fly Delta more than twice a year and check bags, the Gold pays for itself faster.',
    perks: ['2x on Delta purchases','2x at restaurants worldwide','1x on everything else','20% back on Delta in-flight purchases','No annual fee','No foreign transaction fees','Car rental loss and damage insurance'],
    credits: [],
    totalCreditValue: 0,
    earn: { groceries:1, dining:2, flights:2, hotels:1, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['fair','good','excellent'],
    tags: { goal:['travel'], spend:['dining','travel'], fee:['none'], travel:['never','sometimes'] }
  },
  {
    id: 'delta-gold',
    name: 'Delta SkyMiles® Gold American Express Card',
    issuer: 'American Express',
    annualFee: 150,
    annualFeeDisplay: '$0 intro, then $150/yr',
    signupBonus: '70,000 miles (~$840)',
    applyUrl: '#',
    officialUrl: 'https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-gold-american-express-card/',
    why: 'The sweet spot of the Delta card lineup. The free first checked bag alone saves $70+ per round trip — a couple checking one bag on two Delta round trips per year more than covers the $150 fee. Add priority boarding, 15% off award flights, and a $100 Delta Stays credit and the math gets even better for anyone who flies Delta regularly.',
    perks: ['2x on Delta purchases','2x at restaurants worldwide','2x at U.S. supermarkets','1x on everything else','First checked bag free (you + 8 companions)','Priority boarding','15% off Delta award flights','$100 Delta Stays credit','20% back on in-flight purchases','No foreign transaction fees'],
    credits: [
      { name: '$100 Delta Stays Credit', desc: 'Annual statement credit for Delta Stays (powered by Expedia) hotel bookings', value: 100, cadence: 'annual' },
      { name: 'First Checked Bag Free', desc: 'Free first checked bag for you and up to 8 companions on same reservation (~$35/bag saved per flight)', value: 140, cadence: 'excluded' },
      { name: 'Uber One Credit (limited time)', desc: 'Up to $9.99/mo for 6 months toward Uber One membership through June 25, 2026', value: 60, cadence: 'monthly' },
    ],
    totalCreditValue: 300,
    earn: { groceries:2, dining:2, flights:2, hotels:1, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['good','excellent'],
    tags: { goal:['travel'], spend:['dining','groceries','travel'], fee:['low','high'], travel:['sometimes','often'] }
  },
  {
    id: 'delta-plat',
    name: 'Delta SkyMiles® Platinum American Express Card',
    issuer: 'American Express',
    annualFee: 350,
    annualFeeDisplay: '$350/yr',
    signupBonus: '80,000 miles (~$960)',
    applyUrl: '#',
    officialUrl: 'https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-platinum-american-express-card/',
    why: 'The companion certificate is the headline here — every year after renewal you get a round-trip companion ticket (domestic, Caribbean, or Central America) for just taxes and fees. For a couple who flies Delta together once a year, that certificate alone can be worth hundreds. Add the free checked bag, 15% award discount, and $120 Resy credit and the $350 fee is very manageable.',
    perks: ['3x on Delta purchases and eligible hotels','2x at restaurants worldwide','2x at U.S. supermarkets','1x on everything else','Annual companion certificate (Main Cabin)','First checked bag free','Priority boarding','15% off Delta award flights','2,500 MQD Headstart toward Medallion status','No foreign transaction fees'],
    credits: [
      { name: 'Annual Companion Certificate', desc: 'Round-trip companion ticket for Main Cabin on domestic, Caribbean, or Central American Delta flights after card renewal (taxes/fees ~$22-$250 apply)', value: 300, cadence: 'annual' },
      { name: 'First Checked Bag Free', desc: 'Free first checked bag for you and up to 8 companions on same reservation (~$35/bag saved per flight)', value: 140, cadence: 'excluded' },
      { name: '$120 Resy Credit', desc: 'Up to $10/mo in statement credits at U.S. Resy restaurants (enrollment required)', value: 120, cadence: 'monthly' },
      { name: 'Uber One Credit (limited time)', desc: 'Up to $9.99/mo for 12 months toward Uber One membership through June 25, 2026', value: 120, cadence: 'monthly' },
    ],
    totalCreditValue: 680,
    earn: { groceries:2, dining:2, flights:3, hotels:3, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['good','excellent'],
    tags: { goal:['travel'], spend:['dining','travel','groceries'], fee:['low','high'], travel:['sometimes','often'] }
  },
  {
    id: 'delta-reserve',
    name: 'Delta SkyMiles® Reserve American Express Card',
    issuer: 'American Express',
    annualFee: 650,
    annualFeeDisplay: '$650/yr',
    signupBonus: '100,000 miles (~$1,200)',
    applyUrl: '#',
    officialUrl: 'https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-reserve-american-express-card/',
    why: 'The top-tier Delta card for serious Delta loyalists. The big draws are Delta Sky Club access (15 visits/year), Centurion Lounge access when flying Delta, and a first-class companion certificate. If you fly Delta frequently and use the Sky Club even a handful of times a year, the $650 fee becomes very justifiable. The path to Medallion status is also faster with this card.',
    perks: ['3x on Delta purchases','1x on everything else','15 Delta Sky Club visits/year (unlimited at $75k spend)','Centurion Lounge + Escape Lounge access on Delta flights','Annual companion certificate (First Class or Main Cabin)','First checked bag free','Priority boarding','15% off Delta award flights','4 guest passes for Sky Club/year','No foreign transaction fees'],
    credits: [
      { name: 'Annual Companion Certificate', desc: 'Round-trip companion ticket in First Class or Main Cabin on eligible Delta flights after card renewal (taxes/fees apply)', value: 500, cadence: 'annual' },
      { name: 'First Checked Bag Free', desc: 'Free first checked bag for you and up to 8 companions on same reservation (~$35/bag saved per flight)', value: 140, cadence: 'excluded' },
      { name: '15 Delta Sky Club Visits', desc: 'Per Medallion year when flying Delta (~$50/visit value)', value: 750, cadence: 'excluded' },
      { name: 'Centurion Lounge Access', desc: 'When flying on a Delta ticket booked with the Reserve card', value: 429, cadence: 'excluded' },
      { name: 'Uber One Credit (limited time)', desc: 'Up to $9.99/mo for 12 months toward Uber One membership through June 25, 2026', value: 120, cadence: 'monthly' },
    ],
    totalCreditValue: 1939,
    earn: { groceries:1, dining:1, flights:3, hotels:1, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['excellent'],
    tags: { goal:['travel'], spend:['travel'], fee:['high'], travel:['often'] }
  },
  {
    id: 'united-gateway',
    name: 'United Gateway℠ Card',
    issuer: 'Chase',
    annualFee: 0,
    annualFeeDisplay: 'No annual fee',
    signupBonus: '30,000 miles (~$405)',
    applyUrl: '#',
    officialUrl: 'https://creditcards.chase.com/travel-credit-cards/united/united-gateway',
    why: 'The only United card with no annual fee. Worth holding just to keep your MileagePlus account active — and as of April 2, 2026, United cardholders earn significantly more miles on paid flights than non-cardholders. Important caveat: you need to spend $10,000/year on the card to unlock the enhanced earning rates and reduced award prices. Otherwise, the Gateway is mainly useful for keeping a United card in your wallet.',
    perks: ['2x on United purchases (after $10k annual spend)','2x at gas stations and transit','1x on everything else','No annual fee','No foreign transaction fees','2 free checked bags after $10k annual spend','25% discount on United inflight purchases'],
    credits: [],
    totalCreditValue: 0,
    earn: { groceries:1, dining:1, flights:2, hotels:1, gas:2, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['fair','good','excellent'],
    tags: { goal:['travel'], spend:['travel'], fee:['none'], travel:['never','sometimes'] }
  },
  {
    id: 'united-explorer',
    name: 'United℠ Explorer Card',
    issuer: 'Chase',
    annualFee: 150,
    annualFeeDisplay: '$0 intro, then $150/yr',
    signupBonus: '70,000 miles (~$945)',
    applyUrl: '#',
    officialUrl: 'https://creditcards.chase.com/travel-credit-cards/united/united-explorer',
    why: 'A solid mid-tier United card refreshed in 2025. The free first checked bag saves $70+ per round trip — one round trip with a companion more than covers the $150 fee. New credits for rideshare, Instacart, and United Hotels add meaningful value. April 2, 2026 update: earn rates on United flights increased to 3x (up from 2x), and cardholders now get at least 10% off award flights. Two annual United Club passes are a nice bonus for occasional lounge access.',
    perks: ['3x on United purchases (as of April 2, 2026)','2x on dining and hotel stays (booked with hotel)','1x on everything else','Free first checked bag (you + 1 companion)','2 United Club one-time passes/year','Priority boarding','At least 10% off United award flights','Global Entry/TSA PreCheck credit','25% discount on United inflight purchases','No foreign transaction fees'],
    credits: [
      { name: '$100 United Hotels Credit', desc: 'Up to $100 in statement credits on hotel bookings through United Hotels per anniversary year (split $50 semi-annually)', value: 100, cadence: 'semi-annual' },
      { name: '$60 Rideshare Credit', desc: 'Up to $5/mo in statement credits on eligible rideshare purchases (enrollment required)', value: 60, cadence: 'monthly' },
      { name: '$50 Avis/Budget Credit', desc: 'Up to $50 in United TravelBank cash for Avis or Budget rentals booked through cars.united.com per anniversary year', value: 50, cadence: 'annual' },
      { name: '$120 Instacart+ Credit', desc: 'Up to $10/mo in Instacart+ credits, plus 3 months free Instacart+ membership (enrollment required)', value: 120, cadence: 'monthly' },
      { name: 'First Checked Bag Free', desc: 'Free first checked bag for you and one companion on same United reservation (~$35/bag saved per flight)', value: 140, cadence: 'excluded' },
      { name: '2 United Club Passes', desc: 'Two one-time United Club lounge passes per year (~$59 value each)', value: 118, cadence: 'annual' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
    ],
    totalCreditValue: 618,
    earn: { groceries:1, dining:2, flights:3, hotels:2, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['good','excellent'],
    tags: { goal:['travel'], spend:['dining','travel'], fee:['low','high'], travel:['sometimes','often'] }
  },
  {
    id: 'united-quest',
    name: 'United Quest℠ Card',
    issuer: 'Chase',
    annualFee: 350,
    annualFeeDisplay: '$350/yr',
    signupBonus: '90,000 miles + 3,000 PQP (~$1,215)',
    applyUrl: '#',
    officialUrl: 'https://creditcards.chase.com/travel-credit-cards/united/united-quest',
    why: 'The best mid-tier United card for regular flyers. The $200 United TravelBank credit and automatic 10,000-mile award discount together nearly cover the $350 fee on their own. April 2, 2026 update: earn rates on United flights increased to 4x (up from 3x). Two free checked bags, 1,000 bonus PQPs toward elite status, and robust monthly credits for rideshare and Instacart round out a genuinely strong package for United loyalists.',
    perks: ['4x on United purchases (as of April 2, 2026)','2x on travel, dining and select streaming','1x on everything else','Free first and second checked bags (you + 1 companion)','10,000-mile award flight discount every anniversary','At least 10% off United award flights','1,000 bonus PQPs/year toward Medallion status','Priority boarding Group 2','Global Entry/TSA PreCheck credit','No foreign transaction fees'],
    credits: [
      { name: '$200 United TravelBank Credit', desc: 'Automatically deposited each anniversary year to use toward United flights', value: 200, cadence: 'annual' },
      { name: '10,000-Mile Award Discount', desc: 'One 10,000-mile award flight discount each anniversary (~$120-150 value). Earn a second after $20k annual spend.', value: 135, cadence: 'annual' },
      { name: '$150 Renowned Hotels Credit', desc: 'Up to $150 back on prepaid hotel bookings through Renowned Hotels and Resorts per anniversary year', value: 150, cadence: 'annual' },
      { name: '$80 Avis/Budget Credit', desc: 'Up to $80 in United TravelBank cash (two $40 credits) for Avis or Budget rentals per anniversary year', value: 80, cadence: 'annual' },
      { name: '$150 Rideshare Credit', desc: 'Up to $12/mo + $6 bonus in December in statement credits on eligible rideshare (enrollment required)', value: 150, cadence: 'monthly' },
      { name: '$180 Instacart+ Credit', desc: 'Up to $15/mo in Instacart+ credits plus complimentary Instacart+ membership (enrollment required)', value: 180, cadence: 'monthly' },
      { name: 'Free First & Second Checked Bags', desc: 'For you and one companion on same United reservation (~$45/bag saved per flight)', value: 180, cadence: 'excluded' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
    ],
    totalCreditValue: 1105,
    earn: { groceries:1, dining:2, flights:4, hotels:1, gas:1, streaming:2, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['good','excellent'],
    tags: { goal:['travel'], spend:['dining','travel'], fee:['high'], travel:['often','sometimes'] }
  },
  {
    id: 'united-club',
    name: 'United Club℠ Card',
    issuer: 'Chase',
    annualFee: 695,
    annualFeeDisplay: '$695/yr',
    signupBonus: '90,000 miles (~$1,215)',
    applyUrl: '#',
    officialUrl: 'https://creditcards.chase.com/travel-credit-cards/united/club-infinite',
    why: 'The premium United card for serious loyalists. United Club membership alone is worth up to $750 — which technically covers the $695 annual fee before any other benefit. April 2, 2026 update: earn rates on United flights increased to 5x (up from 4x). Note: as of the 2025 refresh, Star Alliance lounge access now requires Premier Gold status or $50k annual spend. Still the best card for frequent United flyers who want lounge access and a fast path to elite status.',
    perks: ['5x on United purchases (as of April 2, 2026)','2x on all other travel and dining','1x on everything else','United Club membership (unlimited access for you + 1 adult guest)','Star Alliance lounge access (requires Premier Gold status or $50k annual spend)','Free first and second checked bags','1,500 bonus PQPs/year toward Medallion status','Priority boarding Group 1','At least 10% off United award flights','No foreign transaction fees'],
    credits: [
      { name: 'United Club Membership', desc: 'Unlimited access to United Club lounges for primary cardholder + 1 adult guest and dependent children under 18 (valued up to $750/yr)', value: 750, cadence: 'excluded' },
      { name: '$200 Renowned Hotels Credit', desc: 'Up to $200 back on prepaid hotel bookings through Renowned Hotels and Resorts per anniversary year', value: 200, cadence: 'annual' },
      { name: '$240 Instacart+ Credit', desc: 'Up to $20/mo in Instacart+ credits plus complimentary Instacart+ membership (enrollment required)', value: 240, cadence: 'monthly' },
      { name: '$150 Rideshare Credit', desc: 'Up to $12/mo + $6 bonus in December in statement credits on eligible rideshare (enrollment required)', value: 150, cadence: 'monthly' },
      { name: '$100 Avis/Budget Credit', desc: 'Up to $100 in United TravelBank cash for Avis or Budget rentals per anniversary year', value: 100, cadence: 'annual' },
      { name: 'Free First & Second Checked Bags', desc: 'For you and one companion on same United reservation', value: 180, cadence: 'excluded' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
    ],
    totalCreditValue: 1650,
    earn: { groceries:1, dining:2, flights:5, hotels:1, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['excellent'],
    tags: { goal:['travel'], spend:['travel','dining'], fee:['high'], travel:['often'] }
  },
  {
    id: 'citi-strata',
    name: 'Citi Strata℠ Card',
    issuer: 'Citi',
    annualFee: 0,
    annualFeeDisplay: 'No annual fee',
    signupBonus: '20,000 pts (~$200)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-strata-credit-card',
    why: 'The best no-annual-fee entry point into the Citi ThankYou ecosystem. Earns 3x on groceries, gas, transit — and one category of your choice (streaming, fitness, live entertainment, etc.). Pair it with the Strata Premier or Elite and your points become transferable to American Airlines and other partners. Note: has a 3% foreign transaction fee, so leave it home when traveling abroad.',
    perks: ['5x on Citi Travel hotels, car rentals & attractions','3x groceries, gas, transit & self-select category','2x dining','1x everything else','No annual fee','0% intro APR for 15 months','Citi Entertainment access'],
    credits: [],
    totalCreditValue: 0,
    earn: { groceries:3, dining:2, flights:1, hotels:5, gas:3, streaming:3, shopping:1, everything:1 },
    pointValue: 0.01,
    creditReq: ['fair','good','excellent'],
    tags: { goal:['cashback','both'], spend:['groceries','dining','everything'], fee:['none'], travel:['never','sometimes'] }
  },
  {
    id: 'citi-strata-premier',
    name: 'Citi Strata Premier® Card',
    issuer: 'Citi',
    annualFee: 95,
    annualFeeDisplay: '$95/yr',
    signupBonus: '60,000 pts (~$1,140)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-strata-premier-credit-card',
    why: 'The best $95 travel card you\'ve probably never heard of. Earns 3x on flights, hotels, dining, groceries AND gas — a broader set of bonus categories than almost any card at this price. The $100 annual hotel credit ($500 minimum stay via Citi Travel) effectively brings the fee to zero. Citi ThankYou Points now transfer to American Airlines AAdvantage — a major addition since mid-2025.',
    perks: ['10x hotels, car rentals & attractions via Citi Travel','3x flights, hotels, dining, groceries & gas','$100 annual hotel credit (on $500+ stay via Citi Travel)','Transfer points to AA, JetBlue, Virgin Atlantic & more','No foreign transaction fees','Access The Reserve luxury hotel collection'],
    credits: [
      { name: '$100 Annual Hotel Credit', desc: 'Once per calendar year, $100 off a single hotel stay of $500 or more (excluding taxes) booked via cititravel.com. Applied instantly at booking.', value: 100, cadence: 'annual' },
    ],
    totalCreditValue: 100,
    earn: { groceries:3, dining:3, flights:3, hotels:3, gas:3, streaming:1, shopping:1, everything:1 },
    pointValue: 0.012,
    creditReq: ['good','excellent'],
    tags: { goal:['travel','both'], spend:['groceries','dining','travel','everything'], fee:['low','high'], travel:['sometimes','often'] }
  },
  {
    id: 'citi-strata-elite',
    name: 'Citi Strata Elite℠ Card',
    issuer: 'Citi',
    annualFee: 595,
    annualFeeDisplay: '$595/yr',
    signupBonus: '75,000 pts (~$1,425)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-strata-elite-credit-card',
    why: 'Citi\'s new premium card launched July 2025 and it\'s genuinely competitive. The $300 hotel credit, $200 Splurge Credit (Best Buy, American Airlines, Live Nation, etc.), and $200 Blacklane chauffeur credit together total $700 before even counting Priority Pass or the 4 Admirals Club passes. The 6x dining rate on Friday/Saturday nights (Citi Nights) is unique. Strong challenger to the Sapphire Reserve and Amex Platinum at a lower fee.',
    perks: ['12x hotels, car rentals & attractions via Citi Travel','6x dining on Citi Nights (Fri/Sat 6pm-6am ET)','3x dining all other times','1.5x on everything else','Priority Pass Select (1,500+ lounges)','4 Admirals Club passes/year','$300 annual hotel credit (Citi Travel, 2-night minimum)','No foreign transaction fees'],
    credits: [
      { name: '$300 Annual Hotel Credit', desc: 'Each calendar year, up to $300 off a hotel stay of 2+ nights booked through cititravel.com', value: 300, cadence: 'annual' },
      { name: '$200 Annual Splurge Credit', desc: 'Up to $200/yr in statement credits on your choice of 2 brands: 1stDibs, American Airlines, Best Buy, Future Personal Training, or Live Nation', value: 200, cadence: 'annual' },
      { name: '$200 Annual Blacklane Credit', desc: '$100 Jan-Jun + $100 Jul-Dec for Blacklane premium chauffeur bookings worldwide', value: 200, cadence: 'semi-annual' },
      { name: '4 Admirals Club Passes', desc: 'Four annual Admirals Club lounge passes (nearly 50 locations, $300+ value)', value: 300, cadence: 'annual' },
      { name: 'Priority Pass Select', desc: 'Complimentary access to 1,500+ airport lounges worldwide for primary cardholder (valued at $469/yr)', value: 469, cadence: 'excluded' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
    ],
    totalCreditValue: 1499,
    earn: { groceries:1.5, dining:6, flights:6, hotels:12, gas:1.5, streaming:1.5, shopping:1.5, everything:1.5 },
    pointValue: 0.012,
    creditReq: ['excellent'],
    tags: { goal:['travel','both'], spend:['dining','travel'], fee:['high'], travel:['often'] }
  },
  {
    id: 'aa-mileup',
    name: 'American Airlines AAdvantage® MileUp® Card',
    issuer: 'Citi',
    annualFee: 0,
    annualFeeDisplay: 'No annual fee',
    signupBonus: '15,000 miles (~$255)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/american-airlines-aadvantage-mileup-credit-card',
    why: 'The simplest way to earn AAdvantage miles with no annual fee. Good for occasional American flyers who want to keep their miles account active and earn on groceries without committing to an annual fee. If you fly AA more than twice a year and check bags, upgrade to the Platinum Select — it pays for itself quickly.',
    perks: ['2x on eligible American Airlines purchases','2x at grocery stores (including delivery)','1x on everything else','25% savings on AA inflight food & beverages','No annual fee'],
    credits: [],
    totalCreditValue: 0,
    earn: { groceries:2, dining:1, flights:2, hotels:1, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.017,
    creditReq: ['fair','good','excellent'],
    tags: { goal:['travel'], spend:['groceries','travel'], fee:['none'], travel:['never','sometimes'] }
  },
  {
    id: 'aa-platinum',
    name: 'Citi® / AAdvantage® Platinum Select® Card',
    issuer: 'Citi',
    annualFee: 99,
    annualFeeDisplay: '$0 intro, then $99/yr',
    signupBonus: '50,000 miles (~$850)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-aadvantage-platinum-select-world-elite-mastercard',
    why: 'The workhorse AA card for regular American flyers. The free first checked bag saves up to $70 per round trip — fly twice a year with a companion and the card pays for itself. Preferred boarding and 25% inflight savings are solid extras. The $125 AA flight discount after $20k annual spend is a nice bonus for heavier spenders.',
    perks: ['2x on AA purchases, dining & gas stations','1x on everything else','First checked bag free (you + 4 companions)','Preferred boarding','25% savings on AA inflight purchases','$125 AA Flight Discount after $20k annual spend','No foreign transaction fees'],
    credits: [
      { name: 'First Checked Bag Free', desc: 'Free first checked bag on domestic AA itineraries for you and up to 4 companions on same reservation (~$35/bag saved per flight)', value: 140, cadence: 'excluded' },
    ],
    totalCreditValue: 140,
    earn: { groceries:1, dining:2, flights:2, hotels:1, gas:2, streaming:1, shopping:1, everything:1 },
    pointValue: 0.017,
    creditReq: ['good','excellent'],
    tags: { goal:['travel'], spend:['dining','travel','gas'], fee:['low','high'], travel:['sometimes','often'] }
  },
  {
    id: 'aa-globe',
    name: 'Citi® / AAdvantage® Globe™ Mastercard®',
    issuer: 'Citi',
    annualFee: 350,
    annualFeeDisplay: '$350/yr',
    signupBonus: '60,000 miles (~$1,020)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-aadvantage-globe-mastercard',
    why: 'The mid-tier AA card that punches above its weight. Four Admirals Club passes per year, an annual companion certificate ($99 + taxes), and a $100 inflight credit make the $350 fee very manageable for someone who flies AA a few times a year. The 6x on AAdvantage Hotels and 3x on AA purchases are strong earn rates for loyalists.',
    perks: ['6x on eligible AAdvantage Hotels bookings','3x on eligible AA purchases','2x dining & eligible Rides and Rails','1x everything else','4 Admirals Club Globe passes/year','Annual companion certificate ($99 + taxes)','First checked bag free (you + 8 companions)','$100 annual inflight credit','Preferred Group 5 boarding','Global Entry/TSA PreCheck credit','No foreign transaction fees'],
    credits: [
      { name: 'Annual Companion Certificate', desc: 'Round-trip domestic American Airlines companion ticket for $99 + taxes/fees per cardmember year', value: 250, cadence: 'annual' },
      { name: '4 Admirals Club Globe Passes', desc: 'Four annual passes to Admirals Club lounges (~$79 value each, 50 locations)', value: 316, cadence: 'annual' },
      { name: '$100 Annual Inflight Credit', desc: 'Statement credits on inflight purchases on American Airlines flights each calendar year', value: 100, cadence: 'annual' },
      { name: '$100 Annual Splurge Credit', desc: 'Up to $100/yr in statement credits on choice of 2 brands: 1stDibs, eligible AAdvantage Hotels, Future Personal Training, or Live Nation', value: 100, cadence: 'annual' },
      { name: '$240 Annual Turo Credit', desc: 'Up to $30 per eligible Turo trip, up to $240 annually (must link card to Turo account)', value: 240, cadence: 'annual' },
      { name: 'First Checked Bag Free', desc: 'Free first checked bag on domestic AA itineraries for you and up to 8 companions (~$35/bag per flight)', value: 140, cadence: 'excluded' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
    ],
    totalCreditValue: 1176,
    earn: { groceries:1, dining:2, flights:3, hotels:6, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.017,
    creditReq: ['good','excellent'],
    tags: { goal:['travel'], spend:['dining','travel'], fee:['high'], travel:['sometimes','often'] }
  },
  {
    id: 'aa-executive',
    name: 'Citi® / AAdvantage® Executive World Elite Mastercard®',
    issuer: 'Citi',
    annualFee: 595,
    annualFeeDisplay: '$595/yr',
    signupBonus: '70,000 miles (~$1,190)',
    applyUrl: '#',
    officialUrl: 'https://www.citi.com/credit-cards/citi-aadvantage-executive-world-elite-mastercard',
    why: 'The top AA card, built around one killer benefit: full Admirals Club membership. An Admirals Club membership alone costs $700-$850 — so the $595 annual fee is actually a discount before counting any other perk. If you fly American regularly and value a quiet, comfortable place to work or wait between flights, this card essentially pays for itself. The $120 each for Grubhub, Lyft, and Avis/Budget round it out.',
    perks: ['4x on eligible AA purchases','10x eligible AAdvantage Hotels & car rentals','1x everything else','Full Admirals Club membership (you + 2 guests or immediate family)','Access to 100+ Admirals Club & partner lounges worldwide','First checked bag free (you + 8 companions)','Priority check-in, screening & boarding on AA','Global Entry/TSA PreCheck credit','Up to 20,000 bonus Loyalty Points/year','No foreign transaction fees'],
    credits: [
      { name: 'Admirals Club Membership', desc: 'Full annual Admirals Club membership for primary cardholder + 2 guests or immediate family. Valued at $700-$850 if purchased separately.', value: 750, cadence: 'excluded' },
      { name: '$120 Annual Grubhub Credit', desc: 'Up to $10/mo in statement credits on eligible Grubhub purchases', value: 120, cadence: 'monthly' },
      { name: '$120 Annual Lyft Credit', desc: '$10/mo after 3 eligible rides in a calendar month', value: 120, cadence: 'monthly' },
      { name: '$120 Annual Avis/Budget Credit', desc: 'Up to $120/yr in statement credits on eligible prepaid Avis or Budget car rentals booked directly on avis.com or budget.com', value: 120, cadence: 'annual' },
      { name: 'First Checked Bag Free', desc: 'Free first checked bag on domestic AA itineraries for you and up to 8 companions (~$35/bag per flight)', value: 140, cadence: 'excluded' },
      { name: 'Global Entry or TSA PreCheck', desc: 'Up to $120 credit every 4 years (~$30/yr value)', value: 30, cadence: 'excluded' },
    ],
    totalCreditValue: 1300,
    earn: { groceries:1, dining:1, flights:4, hotels:10, gas:1, streaming:1, shopping:1, everything:1 },
    pointValue: 0.017,
    creditReq: ['excellent'],
    tags: { goal:['travel'], spend:['travel'], fee:['high'], travel:['often'] }
  }
];

export const BROWSE_CATS = {
  'csp':         ['travel'],
  'csr':         ['travel', 'premium'],
  'amex-plat':   ['travel', 'premium'],
  'amex-gold':   ['travel'],
  'venture-x':   ['travel', 'premium'],
  'double-cash': ['cashback', 'nofee'],
  'cfu':         ['cashback', 'nofee'],
  'delta-blue':    ['travel','nofee'],
  'delta-gold':    ['travel'],
  'delta-plat':    ['travel','premium'],
  'delta-reserve': ['travel','premium'],
  'united-gateway': ['travel','nofee'],
  'united-explorer': ['travel'],
  'united-quest':    ['travel','premium'],
  'united-club':     ['travel','premium'],
  'citi-strata':         ['cashback','nofee'],
  'citi-strata-premier': ['travel'],
  'citi-strata-elite':   ['travel','premium'],
  'aa-mileup':           ['travel','nofee'],
  'aa-platinum':         ['travel'],
  'aa-globe':            ['travel','premium'],
  'aa-executive':        ['travel','premium'],
};

export const TAG_META = {
  travel:   { label: 'Travel',         cls: 'travel'   },
  cashback: { label: 'Cash Back',      cls: 'cashback' },
  nofee:    { label: 'No Annual Fee',  cls: 'nofee'    },
  premium:  { label: 'Premium',        cls: 'premium'  },
};
